---

- name: Setup
  hosts: all
  tasks:
    - name: Ignore PEP 668 because it's silly.
      ansible.builtin.file:
        path: /usr/lib/python3.12/EXTERNALLY-MANAGED
        state: absent
      become: true

    - apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 604800 # 1 week
      become: true

    - pip:
        name: docker