---

- name: Deploy
  hosts: all
  tasks:
    - name: Run Redmine container
      community.docker.docker_container:
        image: pavel123321/redmine
        platform: linux/amd64
        name: myredmine
        state: started
        restart: true
        ports:
          80:3000
        # Закомментил, чтобы в redmine использовалась sqllite, т.к. кластер postgre дорогой
        # env:
        #   REDMINE_DB_POSTGRES: "{{ REDMINE_DB_POSTGRES }}"
        #   REDMINE_DB_USERNAME: "{{ REDMINE_DB_USERNAME }}"
        #   REDMINE_DB_PASSWORD: "{{ REDMINE_DB_PASSWORD }}"
        #   REDMINE_DB_PORT: "{{ REDMINE_DB_PORT }}"
        #   REDMINE_DB_DATABASE: "{{ REDMINE_DB_DATABASE }}"
      become: true
