- name: Setup
  hosts: all
  tags: setup
  roles:
    - { role: geerlingguy.docker, become: yes }
  tasks:
    # to solve error "error: externally-managed-environment" when installing via pip3
    # https://www.jeffgeerling.com/blog/2023/how-solve-error-externally-managed-environment-when-installing-pip3
    - name: Ignore PEP 668 because it's silly.
      ansible.builtin.file:
        path: /usr/lib/python3.12/EXTERNALLY-MANAGED
        state: absent
      become: true

    - name: Install pip
      apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 604800 # 1 week
      become: true

    - name: Install docker python lib
      pip:
        name: docker