---

- name: Deploy
  # В плейбуке для свойства hosts используйте значение all, это важно для системы автоматической проверки проекта (из задания)
  hosts: all
  tags: deploy
  vars_files:
    - ./group_vars/webservers/common.yml
  tasks:
    - name: Run Redmine container
      community.docker.docker_container:
        image: redmine
        platform: linux/amd64
        name: myredmine
        state: started
        restart: true
        ports:
          - "{{ app_port }}:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ redmine_db_postgres }}"
          REDMINE_DB_USERNAME: "{{ redmine_db_username }}"
          REDMINE_DB_PASSWORD: "{{ redmine_db_password }}"
          REDMINE_DB_PORT: "{{ redmine_db_port }}"
          REDMINE_DB_DATABASE: "{{ redmine_db_database }}"
      become: true

- hosts: webservers
  roles:
    - { role: datadog.datadog, become: yes }
  tags: datadog
