---

- name: Setup
  hosts: all
  tags: setup
  roles:
    - { role: geerlingguy.docker, become: yes }
  tasks:
    # to solve error "error: externally-managed-environment" when installing via pip3
    # https://www.jeffgeerling.com/blog/2023/how-solve-error-externally-managed-environment-when-installing-pip3
    - name: Ignore PEP 668 because it's silly.
      ansible.builtin.file:
        path: /usr/lib/python3.12/EXTERNALLY-MANAGED
        state: absent
      become: true

    - name: Install pip
      apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 604800 # 1 week
      become: true

    - name: Install docker python lib
      pip:
        name: docker

- name: Deploy
  # В плейбуке для свойства hosts используйте значение all, это важно для системы автоматической проверки проекта (из задания)
  hosts: all
  tags: deploy
  vars_files:
    - ./group_vars/webservers/common.yml
  tasks:
    - name: Run Redmine container
      community.docker.docker_container:
        image: redmine
        platform: linux/amd64
        name: myredmine
        state: started
        restart: true
        ports:
          - "{{ app_port }}:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ redmine_db_postgres }}"
          REDMINE_DB_USERNAME: "{{ redmine_db_username }}"
          REDMINE_DB_PASSWORD: "{{ redmine_db_password }}"
          REDMINE_DB_PORT: "{{ redmine_db_port }}"
          REDMINE_DB_DATABASE: "{{ redmine_db_database }}"
      become: true

- hosts: webservers
  roles:
    - { role: datadog.datadog, become: yes }
  tags: datadog
